# Generated by Django 5.1.8 on 2025-05-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_choice_quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='attempt_details',
            field=models.JSONField(blank=True, help_text="Stores detailed mistake data (e.g., {question_id: {'user_answer_idx': X, 'correct_answer_idx': Y}})", null=True),
        ),
    ]
