# Generated by Django 5.0.6 on 2025-04-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_choice_quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.CharField(blank=True, help_text='Tag for categorizing questions', max_length=100),
        ),
    ]
