# app.yaml

# Runtime Configuration
runtime: python311
# entrypoint: gunicorn -b :$PORT core.wsgi:application --workers 2 --threads 4 --timeout 60


# Instance Class and Scaling
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.65

# Environment Variables
env_variables:
  DJANGO_SETTINGS_MODULE: "core.settings"
  ENVIRONMENT: "development"

  # Database Configuration
  DB_NAME: "quiz_db"
  DB_USER: "quiz_user"
  # DB_PASSWORD is injected securely from Secret Manager
  DB_HOST: "/cloudsql/akbar-quiz-app-april-2025:us-central1:akbar-quiz-db"
  DB_PORT: "5432"

  # Application URL (for ALLOWED_HOSTS)
  APPENGINE_URL: "akbar-quiz-app-april-2025.uc.r.appspot.com"

  # Securely Injected Secrets
  SECRET_KEY: "projects/akbar-quiz-app-april-2025/secrets/django-secret-key/versions/latest"
  DB_PASSWORD: "projects/akbar-quiz-app-april-2025/secrets/db-password/versions/latest"

# Cloud SQL Connection
beta_settings:
  cloud_sql_instances: "akbar-quiz-app-april-2025:us-central1:akbar-quiz-db"

# Request Handlers
handlers:
  - url: /.*
    script: auto
    secure: always