# Generated by Django 5.1.8 on 2025-05-09 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multi_choice_quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The display name of the category.', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='A unique slug for URLs, typically auto-generated from the name.', max_length=110, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the category (optional).')),
                ('quizzes', models.ManyToManyField(blank=True, help_text='Quizzes belonging to this public category.', related_name='system_categories', to='multi_choice_quiz.quiz')),
            ],
            options={
                'verbose_name': 'System Category',
                'verbose_name_plural': 'System Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the user's private collection.", max_length=100)),
                ('description', models.TextField(blank=True, help_text='A brief description of the collection (optional).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quizzes', models.ManyToManyField(blank=True, help_text='Quizzes the user has added to this collection.', related_name='user_collections', to='multi_choice_quiz.quiz')),
                ('user', models.ForeignKey(help_text='The user who owns this collection.', on_delete=django.db.models.deletion.CASCADE, related_name='user_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Collection',
                'verbose_name_plural': 'User Collections',
                'ordering': ['user', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
