module_dict = {
    1: "Project Setup & Configuration",
    2: "Data Modeling - The Quiz Structure",
    3: "Handling Requests & Rendering Pages",
    4: "Frontend Interactivity - Alpine.js & Static Files",
    5: "User Authentication & Management",
    6: "Interacting with the Frontend - API Endpoint",
    7: "Data Import & Utilities",
    8: "Testing Django Application",
    9: "Progressive Web App (PWA) Features"
}




table_of_contents_data = [
    # Module 1
    {"ModuleNumber": 1, "ItemNumber": "1",   "ParentItemNumber": None, "ItemType": "Module",   "ItemText": "Project Setup & Configuration"},
    {"ModuleNumber": 1, "ItemNumber": "1.1", "ParentItemNumber": "1",  "ItemType": "Sub-item","ItemText": "Django Project Structure (Core Directory, Entry Point)"},
    {"ModuleNumber": 1, "ItemNumber": "1.2", "ParentItemNumber": "1",  "ItemType": "Sub-item","ItemText": "Core Project Settings"},
    {"ModuleNumber": 1, "ItemNumber": None,  "ParentItemNumber": "1.2","ItemType": "Detail",  "ItemText": "Identifying Django Apps"},
    {"ModuleNumber": 1, "ItemNumber": None,  "ParentItemNumber": "1.2","ItemType": "Detail",  "ItemText": "Understanding Request/Response Processing Flow"},
    {"ModuleNumber": 1, "ItemNumber": None,  "ParentItemNumber": "1.2","ItemType": "Detail",  "ItemText": "Database Configuration (Local vs. Production)"},
    {"ModuleNumber": 1, "ItemNumber": None,  "ParentItemNumber": "1.2","ItemType": "Detail",  "ItemText": "Template Engine Configuration"},
    {"ModuleNumber": 1, "ItemNumber": None,  "ParentItemNumber": "1.2","ItemType": "Detail",  "ItemText": "Static File Handling Configuration"},
    {"ModuleNumber": 1, "ItemNumber": None,  "ParentItemNumber": "1.2","ItemType": "Detail",  "ItemText": "Root URL Configuration"},
    {"ModuleNumber": 1, "ItemNumber": "1.3", "ParentItemNumber": "1",  "ItemType": "Sub-item","ItemText": "Environment Management"},
    {"ModuleNumber": 1, "ItemNumber": "1.4", "ParentItemNumber": "1",  "ItemType": "Sub-item","ItemText": "Overriding Settings for Local Development & Debugging Tools"},
    {"ModuleNumber": 1, "ItemNumber": "1.5", "ParentItemNumber": "1",  "ItemType": "Sub-item","ItemText": "Main URL Routing"},
    {"ModuleNumber": 1, "ItemNumber": None,  "ParentItemNumber": "1.5","ItemType": "Detail",  "ItemText": "Including URLs from Individual Apps"},
    {"ModuleNumber": 1, "ItemNumber": None,  "ParentItemNumber": "1.5","ItemType": "Detail",  "ItemText": "Configuring the Admin Site URL"},
    {"ModuleNumber": 1, "ItemNumber": None,  "ParentItemNumber": "1.5","ItemType": "Detail",  "ItemText": "Integrating Authentication URLs"},

    # Module 2
    {"ModuleNumber": 2, "ItemNumber": "2",   "ParentItemNumber": None, "ItemType": "Module",   "ItemText": "Data Modeling - Application Structure"},
    {"ModuleNumber": 2, "ItemNumber": "2.1", "ParentItemNumber": "2",  "ItemType": "Sub-item","ItemText": "Introduction to Django Models & ORM"},
    {"ModuleNumber": 2, "ItemNumber": "2.2", "ParentItemNumber": "2",  "ItemType": "Sub-item","ItemText": "Defining Core Entities"},
    {"ModuleNumber": 2, "ItemNumber": "2.3", "ParentItemNumber": "2",  "ItemType": "Sub-item","ItemText": "Defining Related Entities (Primary Models)"},
    {"ModuleNumber": 2, "ItemNumber": None,  "ParentItemNumber": "2.3","ItemType": "Detail",  "ItemText": "Defining Fields"},
    {"ModuleNumber": 2, "ItemNumber": None,  "ParentItemNumber": "2.3","ItemType": "Detail",  "ItemText": "Configuring Many-to-Many Relationships"},
    {"ModuleNumber": 2, "ItemNumber": None,  "ParentItemNumber": "2.3","ItemType": "Detail",  "ItemText": "Adding Model Methods"},
    {"ModuleNumber": 2, "ItemNumber": "2.4", "ParentItemNumber": "2",  "ItemType": "Sub-item","ItemText": "Defining Related Entities (Secondary Models)"},
    {"ModuleNumber": 2, "ItemNumber": None,  "ParentItemNumber": "2.4","ItemType": "Detail",  "ItemText": "Defining Fields"},
    {"ModuleNumber": 2, "ItemNumber": None,  "ParentItemNumber": "2.4","ItemType": "Detail",  "ItemText": "Configuring Foreign Key Relationships"},
    {"ModuleNumber": 2, "ItemNumber": None,  "ParentItemNumber": "2.4","ItemType": "Detail",  "ItemText": "Adding Model Methods"},
    {"ModuleNumber": 2, "ItemNumber": None,  "ParentItemNumber": "2.4","ItemType": "Detail",  "ItemText": "Preparing Data for Frontend Use"},
    {"ModuleNumber": 2, "ItemNumber": "2.5", "ParentItemNumber": "2",  "ItemType": "Sub-item","ItemText": "Defining Sub-Components of Items"},
    {"ModuleNumber": 2, "ItemNumber": None,  "ParentItemNumber": "2.5","ItemType": "Detail",  "ItemText": "Defining Fields"},
    {"ModuleNumber": 2, "ItemNumber": None,  "ParentItemNumber": "2.5","ItemType": "Detail",  "ItemText": "Configuring Foreign Key Relationships"},
    {"ModuleNumber": 2, "ItemNumber": "2.6", "ParentItemNumber": "2",  "ItemType": "Sub-item","ItemText": "Tracking User Interaction Data"},
    {"ModuleNumber": 2, "ItemNumber": None,  "ParentItemNumber": "2.6","ItemType": "Detail",  "ItemText": "Defining Fields (Scores, Timestamps, etc.)"},
    {"ModuleNumber": 2, "ItemNumber": None,  "ParentItemNumber": "2.6","ItemType": "Detail",  "ItemText": "Configuring Relationships with Core Entities and Users (Including Anonymous Users)"},
    {"ModuleNumber": 2, "ItemNumber": "2.7", "ParentItemNumber": "2",  "ItemType": "Sub-item","ItemText": "Database Migrations (Concept and Usage)"},

    # Module 3
    {"ModuleNumber": 3, "ItemNumber": "3",   "ParentItemNumber": None, "ItemType": "Module",   "ItemText": "Handling Requests & Rendering Pages"},
    {"ModuleNumber": 3, "ItemNumber": "3.1", "ParentItemNumber": "3",  "ItemType": "Sub-item","ItemText": "Introduction to Django Views (Function-Based) and the Request-Response Cycle"},
    {"ModuleNumber": 3, "ItemNumber": "3.2", "ParentItemNumber": "3",  "ItemType": "Sub-item","ItemText": "Structuring Core Pages"},
    {"ModuleNumber": 3, "ItemNumber": None,  "ParentItemNumber": "3.2","ItemType": "Detail",  "ItemText": "Defining Views for Main Pages (Home, Lists, Detail Views, etc.)"},
    {"ModuleNumber": 3, "ItemNumber": None,  "ParentItemNumber": "3.2","ItemType": "Detail",  "ItemText": "Defining App-Specific URLs"},
    {"ModuleNumber": 3, "ItemNumber": None,  "ParentItemNumber": "3.2","ItemType": "Detail",  "ItemText": "Structuring App Templates"},
    {"ModuleNumber": 3, "ItemNumber": None,  "ParentItemNumber": "3.2","ItemType": "Detail",  "ItemText": "Creating a Base Template: Structure, Styling Integration, Script Inclusion, Header/Footer"},
    {"ModuleNumber": 3, "ItemNumber": None,  "ParentItemNumber": "3.2","ItemType": "Detail",  "ItemText": "Creating Child Templates: Extending the Base, Using Context Data, Using Template Tags"},
    {"ModuleNumber": 3, "ItemNumber": "3.3", "ParentItemNumber": "3",  "ItemType": "Sub-item","ItemText": "Structuring Feature-Specific Views & Templates"},
    {"ModuleNumber": 3, "ItemNumber": None,  "ParentItemNumber": "3.3","ItemType": "Detail",  "ItemText": "Defining Views for Interactive Features"},
    {"ModuleNumber": 3, "ItemNumber": None,  "ParentItemNumber": "3.3","ItemType": "Detail",  "ItemText": "Fetching Specific Data and Preparing It for the Frontend"},
    {"ModuleNumber": 3, "ItemNumber": None,  "ParentItemNumber": "3.3","ItemType": "Detail",  "ItemText": "Structuring Feature Templates"},

    # Module 4
    {"ModuleNumber": 4, "ItemNumber": "4",   "ParentItemNumber": None, "ItemType": "Module",   "ItemText": "Frontend Interactivity & Static Files"},
    {"ModuleNumber": 4, "ItemNumber": "4.1", "ParentItemNumber": "4",  "ItemType": "Sub-item","ItemText": "Introduction to Static Files (CSS & JavaScript)"},
    {"ModuleNumber": 4, "ItemNumber": "4.2", "ParentItemNumber": "4",  "ItemType": "Sub-item","ItemText": "Integrating a Frontend JavaScript Library or Framework"},
    {"ModuleNumber": 4, "ItemNumber": "4.3", "ParentItemNumber": "4",  "ItemType": "Sub-item","ItemText": "Implementing Frontend Components and Logic"},
    {"ModuleNumber": 4, "ItemNumber": None,  "ParentItemNumber": "4.3","ItemType": "Detail",  "ItemText": "Reading Initial Data from the Backend"},
    {"ModuleNumber": 4, "ItemNumber": None,  "ParentItemNumber": "4.3","ItemType": "Detail",  "ItemText": "State Management (Variables)"},
    {"ModuleNumber": 4, "ItemNumber": None,  "ParentItemNumber": "4.3","ItemType": "Detail",  "ItemText": "Computed Properties (Derived State)"},
    {"ModuleNumber": 4, "ItemNumber": None,  "ParentItemNumber": "4.3","ItemType": "Detail",  "ItemText": "Defining Core Methods (Initialization, Handling User Actions, Navigation, Reset)"},
    {"ModuleNumber": 4, "ItemNumber": None,  "ParentItemNumber": "4.3","ItemType": "Detail",  "ItemText": "Processing User Input and Providing Feedback"},
    {"ModuleNumber": 4, "ItemNumber": None,  "ParentItemNumber": "4.3","ItemType": "Detail",  "ItemText": "Calculating and Displaying Results"},
    {"ModuleNumber": 4, "ItemNumber": None,  "ParentItemNumber": "4.3","ItemType": "Detail",  "ItemText": "Applying Dynamic Styling Based on State"},
    {"ModuleNumber": 4, "ItemNumber": None,  "ParentItemNumber": "4.3","ItemType": "Detail",  "ItemText": "Using Timers for UI Effects"},
    {"ModuleNumber": 4, "ItemNumber": "4.4", "ParentItemNumber": "4",  "ItemType": "Sub-item","ItemText": "Styling the Application Interface"},
    {"ModuleNumber": 4, "ItemNumber": None,  "ParentItemNumber": "4.4","ItemType": "Detail",  "ItemText": "Basic Styles and Layout"},
    {"ModuleNumber": 4, "ItemNumber": None,  "ParentItemNumber": "4.4","ItemType": "Detail",  "ItemText": "Responsive Design"},
    {"ModuleNumber": 4, "ItemNumber": None,  "ParentItemNumber": "4.4","ItemType": "Detail",  "ItemText": "Styling Specific Elements (e.g., Code Blocks)"},
    {"ModuleNumber": 4, "ItemNumber": None,  "ParentItemNumber": "4.4","ItemType": "Detail",  "ItemText": "Adding Animations"},
    {"ModuleNumber": 4, "ItemNumber": "4.5", "ParentItemNumber": "4",  "ItemType": "Sub-item","ItemText": "Including Necessary Scripts in Templates"},

    # Module 5
    {"ModuleNumber": 5, "ItemNumber": "5",   "ParentItemNumber": None, "ItemType": "Module",   "ItemText": "User Authentication & Management"},
    {"ModuleNumber": 5, "ItemNumber": "5.1", "ParentItemNumber": "5",  "ItemType": "Sub-item","ItemText": "Django's Built-in Authentication System Overview"},
    {"ModuleNumber": 5, "ItemNumber": "5.2", "ParentItemNumber": "5",  "ItemType": "Sub-item","ItemText": "Integrating Authentication URLs into the Project"},
    {"ModuleNumber": 5, "ItemNumber": "5.3", "ParentItemNumber": "5",  "ItemType": "Sub-item","ItemText": "Customizing Authentication Templates"},
    {"ModuleNumber": 5, "ItemNumber": None,  "ParentItemNumber": "5.3","ItemType": "Detail",  "ItemText": "Login Page Template"},
    {"ModuleNumber": 5, "ItemNumber": None,  "ParentItemNumber": "5.3","ItemType": "Detail",  "ItemText": "Logout Confirmation Template"},
    {"ModuleNumber": 5, "ItemNumber": None,  "ParentItemNumber": "5.3","ItemType": "Detail",  "ItemText": "Password Change Templates"},
    {"ModuleNumber": 5, "ItemNumber": None,  "ParentItemNumber": "5.3","ItemType": "Detail",  "ItemText": "Password Reset Flow Templates (Form, Done, Email, Confirm, Complete)"},
    {"ModuleNumber": 5, "ItemNumber": "5.4", "ParentItemNumber": "5",  "ItemType": "Sub-item","ItemText": "User Signup Process"},
    {"ModuleNumber": 5, "ItemNumber": None,  "ParentItemNumber": "5.4","ItemType": "Detail",  "ItemText": "Using and Customizing User Creation Forms"},
    {"ModuleNumber": 5, "ItemNumber": None,  "ParentItemNumber": "5.4","ItemType": "Detail",  "ItemText": "Handling Form Submissions (GET vs. POST)"},
    {"ModuleNumber": 5, "ItemNumber": None,  "ParentItemNumber": "5.4","ItemType": "Detail",  "ItemText": "Form Validation"},
    {"ModuleNumber": 5, "ItemNumber": None,  "ParentItemNumber": "5.4","ItemType": "Detail",  "ItemText": "Saving New Users"},
    {"ModuleNumber": 5, "ItemNumber": None,  "ParentItemNumber": "5.4","ItemType": "Detail",  "ItemText": "Automatic Login after Signup"},
    {"ModuleNumber": 5, "ItemNumber": None,  "ParentItemNumber": "5.4","ItemType": "Detail",  "ItemText": "Displaying Form Errors in Templates"},
    {"ModuleNumber": 5, "ItemNumber": "5.5", "ParentItemNumber": "5",  "ItemType": "Sub-item","ItemText": "User Profile Pages"},
    {"ModuleNumber": 5, "ItemNumber": None,  "ParentItemNumber": "5.5","ItemType": "Detail",  "ItemText": "Protecting Views (Requiring Login)"},
    {"ModuleNumber": 5, "ItemNumber": None,  "ParentItemNumber": "5.5","ItemType": "Detail",  "ItemText": "Accessing Information about the Logged-in User"},
    {"ModuleNumber": 5, "ItemNumber": None,  "ParentItemNumber": "5.5","ItemType": "Detail",  "ItemText": "Displaying User Details and Associated Historical Data"},

    # Module 6
    {"ModuleNumber": 6, "ItemNumber": "6",   "ParentItemNumber": None, "ItemType": "Module",   "ItemText": "Interacting with the Frontend - API Endpoints"},
    {"ModuleNumber": 6, "ItemNumber": "6.1", "ParentItemNumber": "6",  "ItemType": "Sub-item","ItemText": "Concept: Backend API for Frontend Data Submission"},
    {"ModuleNumber": 6, "ItemNumber": "6.2", "ParentItemNumber": "6",  "ItemType": "Sub-item","ItemText": "Implementing API Views"},
    {"ModuleNumber": 6, "ItemNumber": None,  "ParentItemNumber": "6.2","ItemType": "Detail",  "ItemText": "Specifying Allowed HTTP Methods (e.g., POST)"},
    {"ModuleNumber": 6, "ItemNumber": None,  "ParentItemNumber": "6.2","ItemType": "Detail",  "ItemText": "Parsing Incoming Data (e.g., JSON)"},
    {"ModuleNumber": 6, "ItemNumber": None,  "ParentItemNumber": "6.2","ItemType": "Detail",  "ItemText": "Data Validation"},
    {"ModuleNumber": 6, "ItemNumber": None,  "ParentItemNumber": "6.2","ItemType": "Detail",  "ItemText": "Creating or Updating Backend Records"},
    {"ModuleNumber": 6, "ItemNumber": None,  "ParentItemNumber": "6.2","ItemType": "Detail",  "ItemText": "Returning API Responses (e.g., JSON)"},
    {"ModuleNumber": 6, "ItemNumber": "6.3", "ParentItemNumber": "6",  "ItemType": "Sub-item","ItemText": "Connecting Frontend to Backend via API"},
    {"ModuleNumber": 6, "ItemNumber": None,  "ParentItemNumber": "6.3","ItemType": "Detail",  "ItemText": "Using Standard Web APIs (e.g., Fetch API)"},
    {"ModuleNumber": 6, "ItemNumber": None,  "ParentItemNumber": "6.3","ItemType": "Detail",  "ItemText": "Sending Data Requests (e.g., POST with JSON Payload)"},
    {"ModuleNumber": 6, "ItemNumber": None,  "ParentItemNumber": "6.3","ItemType": "Detail",  "ItemText": "Handling API Success and Error Responses"},
    {"ModuleNumber": 6, "ItemNumber": "6.4", "ParentItemNumber": "6",  "ItemType": "Sub-item","ItemText": "CSRF Considerations for API Endpoints"},

    # Module 7
    {"ModuleNumber": 7, "ItemNumber": "7",   "ParentItemNumber": None, "ItemType": "Module",   "ItemText": "Data Import & Utilities"},
    {"ModuleNumber": 7, "ItemNumber": "7.1", "ParentItemNumber": "7",  "ItemType": "Sub-item","ItemText": "Creating Management Commands for Data Import & Export"},
    {"ModuleNumber": 7, "ItemNumber": None,  "ParentItemNumber": "7.1","ItemType": "Detail",  "ItemText": "Adding Sample Data"},
    {"ModuleNumber": 7, "ItemNumber": None,  "ParentItemNumber": "7.1","ItemType": "Detail",  "ItemText": "Importing Data from Files"},
    {"ModuleNumber": 7, "ItemNumber": None,  "ParentItemNumber": "7.1","ItemType": "Detail",  "ItemText": "Using Libraries for Data Processing"},
    {"ModuleNumber": 7, "ItemNumber": None,  "ParentItemNumber": "7.1","ItemType": "Detail",  "ItemText": "Implementing Data Processing Logic (e.g., Sampling, Splitting)"},
    {"ModuleNumber": 7, "ItemNumber": "7.2", "ParentItemNumber": "7",  "ItemType": "Sub-item","ItemText": "Transformation Logic"},
    {"ModuleNumber": 7, "ItemNumber": None,  "ParentItemNumber": "7.2","ItemType": "Detail",  "ItemText": "Converting Data Formats (e.g., Source → Internal Model Format)"},
    {"ModuleNumber": 7, "ItemNumber": None,  "ParentItemNumber": "7.2","ItemType": "Detail",  "ItemText": "Preparing Data for Frontend Use (e.g., Structuring JSON)"},
    {"ModuleNumber": 7, "ItemNumber": "7.3", "ParentItemNumber": "7",  "ItemType": "Sub-item","ItemText": "Utility Functions"},
    {"ModuleNumber": 7, "ItemNumber": None,  "ParentItemNumber": "7.3","ItemType": "Detail",  "ItemText": "Helper Functions for Data Import"},
    {"ModuleNumber": 7, "ItemNumber": None,  "ParentItemNumber": "7.3","ItemType": "Detail",  "ItemText": "Functions for Data Cleaning and Curation"},

    # Module 8
    {"ModuleNumber": 8, "ItemNumber": "8",   "ParentItemNumber": None, "ItemType": "Module",   "ItemText": "Testing the Application"},
    {"ModuleNumber": 8, "ItemNumber": "8.1", "ParentItemNumber": "8",  "ItemType": "Sub-item","ItemText": "Introduction to Testing in Django/Python"},
    {"ModuleNumber": 8, "ItemNumber": "8.2", "ParentItemNumber": "8",  "ItemType": "Sub-item","ItemText": "Pytest Basics and Configuration"},
    {"ModuleNumber": 8, "ItemNumber": "8.3", "ParentItemNumber": "8",  "ItemType": "Sub-item","ItemText": "Pytest Fixtures"},
    {"ModuleNumber": 8, "ItemNumber": None,  "ParentItemNumber": "8.3","ItemType": "Detail",  "ItemText": "Understanding Fixture Scope"},
    {"ModuleNumber": 8, "ItemNumber": None,  "ParentItemNumber": "8.3","ItemType": "Detail",  "ItemText": "Fixtures for Setting Up Test Environment (e.g., Test Server)"},
    {"ModuleNumber": 8, "ItemNumber": None,  "ParentItemNumber": "8.3","ItemType": "Detail",  "ItemText": "Fixtures for Capturing Errors During Tests"},
    {"ModuleNumber": 8, "ItemNumber": "8.4", "ParentItemNumber": "8",  "ItemType": "Sub-item","ItemText": "End-to-End Testing with Playwright"},
    {"ModuleNumber": 8, "ItemNumber": None,  "ParentItemNumber": "8.4","ItemType": "Detail",  "ItemText": "Simulating User Interactions"},
    {"ModuleNumber": 8, "ItemNumber": None,  "ParentItemNumber": "8.4","ItemType": "Detail",  "ItemText": "Using Test Environment & Error Capturing Fixtures in E2E Tests"},
    {"ModuleNumber": 8, "ItemNumber": "8.5", "ParentItemNumber": "8",  "ItemType": "Sub-item","ItemText": "Test Runners & Scripts"},
    {"ModuleNumber": 8, "ItemNumber": None,  "ParentItemNumber": "8.5","ItemType": "Detail",  "ItemText": "Purpose: Automating Test Suite Execution"},
    {"ModuleNumber": 8, "ItemNumber": None,  "ParentItemNumber": "8.5","ItemType": "Detail",  "ItemText": "Ensuring Test Prerequisites (Server, Data)"},
    {"ModuleNumber": 8, "ItemNumber": "8.6", "ParentItemNumber": "8",  "ItemType": "Sub-item","ItemText": "Interpreting Test Results (Passing vs. Failing, Error Output)"},
    {"ModuleNumber": 8, "ItemNumber": "8.7", "ParentItemNumber": "8",  "ItemType": "Sub-item","ItemText": "Integrating Pytest with Django (Using Markers for Database Access)"},

    # Module 9
    {"ModuleNumber": 9, "ItemNumber": "9",   "ParentItemNumber": None, "ItemType": "Module",   "ItemText": "Progressive Web App (PWA) Features"},
    {"ModuleNumber": 9, "ItemNumber": "9.1", "ParentItemNumber": "9",  "ItemType": "Sub-item","ItemText": "Overview of a PWA Library (e.g., django-pwa)"},
    {"ModuleNumber": 9, "ItemNumber": "9.2", "ParentItemNumber": "9",  "ItemType": "Sub-item","ItemText": "Configuration in Project Settings"},
    {"ModuleNumber": 9, "ItemNumber": "9.3", "ParentItemNumber": "9",  "ItemType": "Sub-item","ItemText": "Manifest File Setup"},
    {"ModuleNumber": 9, "ItemNumber": "9.4", "ParentItemNumber": "9",  "ItemType": "Sub-item","ItemText": "Service Worker Implementation"},
    {"ModuleNumber": 9, "ItemNumber": "9.5", "ParentItemNumber": "9",  "ItemType": "Sub-item","ItemText": "PWA Meta Tags in Base Templates"},
]

